name: Print features

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
  workflow_dispatch:

jobs:
  print:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Windows latest - MSVC",
              os: windows-latest,
              cc: "cl",
              cxx: "cl",
            }
          - {
              name: "Ubuntu 24.04 - GCC",
              os: ubuntu-24.04,
              cc: "gcc",
              cxx: "g++",
            }
          - {
              name: "Ubuntu 24.04 - Clang",
              os: ubuntu-24.04,
              cc: "clang",
              cxx: "clang++",
            }
          - {
              name: "macOS 14",
              os: macos-14,
              cc: "clang",
              cxx: "clang++",
            }
    steps:
      - uses: actions/checkout@v4

      - name: CMake configure
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: CMake build
        run: cmake --build build --target=print-features
