name: Print features

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  print:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Windows latest - MSVC",
              os: windows-latest,
              cc: "cl",
              cxx: "cl",
            }
          - {
              name: "Ubuntu latest - GCC",
              os: ubuntu-latest,
              cc: "gcc",
              cxx: "g++",
            }
          - {
              name: "Ubuntu latest - GCC 12",
              os: ubuntu-latest,
              cc: "gcc-12",
              cxx: "g++-12",
            }
          - {
              name: "Ubuntu latest - Clang",
              os: ubuntu-latest,
              cc: "clang",
              cxx: "clang++",
            }
          - {
              name: "Ubuntu latest - Clang 15",
              os: ubuntu-latest,
              cc: "clang-15",
              cxx: "clang++-15",
            }
          - {
              name: "macOS 13",
              os: macos-13,
              cc: "clang",
              cxx: "clang++",
            }
    steps:
      - uses: actions/checkout@v4

      - name: CMake configure
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: CMake build
        run: cmake --build build --target=print-features
